name: binarytree
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        default: 'none'
      submodule-cache-key:
        required: false
        default: 'none'

# No default working-directory — we install at the repo root on purpose

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-binarytree
  cancel-in-progress: true

jobs:
  test-binarytree:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js 20 (with pnpm store cache)
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'pnpm'

      # Install dependencies from the WORKSPACE ROOT
      - name: Install dependencies (workspace)
        working-directory: ${{ github.workspace }}
        run: pnpm install --frozen-lockfile

      # Build only the binarytree package
      - name: Build @ethereumjs/binarytree
        run: pnpm -w -r --filter "@ethereumjs/binarytree" run build

      # Test only the binarytree package
      - name: Test @ethereumjs/binarytree
        run: pnpm -w -r --filter "@ethereumjs/binarytree" run test
