name: Block
on:
  push:
    branches: [master, develop]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/block

defaults:
  run:
    working-directory: packages/block

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-block:
    needs: 'build-monorepo'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: 'Load cache'
        uses: 'actions/cache@v3'
        with:
          path: '.'
          key: '${{ runner.os }}-node-18-${{ git rev-parse HEAD }}'
          restore-keys: '${{ runner.os }}-node-18'