name: Block
on:
  workflow_call:
    inputs:
      cache-key:
        required: false
        type: string
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/block

defaults:
  run:
    working-directory: packages/block

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-block
  cancel-in-progress: true

jobs:
  test-block:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.cache-key }}

      # - name: Install Dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm ci

      - run: npm run lint      
      - run: npm run coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace}}/packages/block/coverage/lcov.info
          flags: block
