name: Browser
on:
  workflow_call:
    inputs:
      cache-key:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      cache-key:
        required: false
        type: string

env:
  cwd: ${{github.workspace}}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  test-all-browser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # necessary for block tests to load ethereum/tests
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.cache-key }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run install-browser-deps

      - run: npm run test:browser --workspaces --if-present



