name: Browser
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
      submodule-cache-key:
          required: true
          type: string
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        default: 'none'
      submodule-cache-key:
        required: false
        default: 'none'

env:
  cwd: ${{github.workspace}}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-browser
  cancel-in-progress: true

jobs:
  test-all-browser:
    if: contains(join(github.event.pull_request.labels.*.name, ' '), 'test no browser') == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # We clone the repo and submodules if triggered from work-flow dispatch
      - if: inputs.submodule-cache-key == 'none'
        uses: actions/checkout@v5
        with:
          submodules: recursive

      # We restore the code/deps from cache if triggered from workflow_call (i.e. have valid cache key)
      - if: inputs.dep-cache-key != 'none' 
        uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}
  
      - uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install Dependencies (if called from workflow_dispatch)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
        working-directory: ${{ github.workspace }}

      - if: inputs.submodule-cache-key != 'none'
        uses: actions/cache/restore@v4
        name: Restore ethereum-tests from cache if available
        id: submodules-cache
        with:
          path: ${{github.workspace}}/packages/ethereum-tests
          key: ${{ inputs.submodule-cache-key }}

      - run: pnpm run install-browser-deps
      - run: npx playwright install --with-deps

      - run: pnpm run test:browser

