name: Build
on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
        working-directory: ${{github.workspace}}

      - uses: actions/cache@v3
        with:
          path: ${{github.workspace}}
          key: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-build

      - run: echo ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-build
      
  call-block:
    needs: build
    uses: ./.github/workflows/block-build.yml
    with:
      cache-key: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-build
  
  call-devp2p:
    needs: build
    uses: ./.github/workflows/devp2p-build.yml

  call-common:
    needs: build
    uses: ./.github/workflows/common-build.yml

  call-ethash:
    needs: build
    uses: ./.github/workflows/ethash-build.yml

  call-rlp:
    needs: build
    uses: ./.github/workflows/rlp-build.yml

  call-trie:
    needs: build
    uses: ./.github/workflows/trie-build.yml