name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'pnpm'          # sets up pnpm store cache ONLY

      # INSTALL PNPM (puts pnpm on PATH)
      - uses: pnpm/action-setup@v4
        with:
          # If your root package.json has: { "packageManager": "pnpm@9.12.0" }
          # you can use 'auto' here. Otherwise pick a version.
          version: '9'
          run_install: false

      - name: Check pnpm is available
        run: |
          pnpm -v
          which pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
