name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'   # only caching, not installing pnpm

      # ↓ This actually installs pnpm and puts it on PATH
      - uses: pnpm/action-setup@v4
        with:
          version: 9         # or match your repo
          run_install: false # we'll run install explicitly

      - name: Show pnpm version
        run: pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
