name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'pnpm'

      # This is what installs pnpm and adds it to PATH
      - uses: pnpm/action-setup@v4
        with:
          version: auto
          run_install: false

      - name: Verify pnpm
        run: |
          set -eux
          pnpm -v
          command -v pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
