name: Common
on:
  workflow_call:
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/common

defaults:
  run:
    working-directory: packages/common

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-common
  cancel-in-progress: true

jobs:
  test-common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}
          key: ${{hashFiles('packages/**/src')}}

      - run: npm run lint
      - run: npm run coverage

      - uses: codecov/codecov-action@v3
        with:
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: common
        if: ${{ matrix.node-version == 16 }}
