name: Devp2p
on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/devp2p

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-devp2p
  cancel-in-progress: true

jobs:
  test-devp2p:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.cache-key }}

      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: npm run test

      - uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/packages/devp2p/coverage/lcov.info
          flags: devp2p

      - run: npm run lint
