name: EVM
on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/evm

defaults:
  run:
    working-directory: packages/evm

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-evm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.cache-key }}

      - run: npm run lint
      - run: npm run coverage

      - uses: codecov/codecov-action@v3
        with:
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: evm
        if: ${{ matrix.node-version == 16 }}
