name: Packages examples
on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.cache-key }}
