name: RLP/Ethash/Genesis/Wallet Build
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        default: 'none'
      submodule-cache-key:
        required: false

env:
  cwd: ${{github.workspace}}/packages/rlp # This doesn't appear to matter since code coverage finds all of the reports

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-static
  cancel-in-progress: true

jobs:
  test-static:
    runs-on: ubuntu-latest

    steps:
      # We clone the repo and submodules if triggered from work-flow dispatch
      - if: inputs.submodule-cache-key == 'none'
        uses: actions/checkout@v5

      # We restore the code/deps from cache if triggered from workflow_call (i.e. have valid cache key)
      - if: inputs.dep-cache-key != 'none' 
        uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
        working-directory: ${{ github.workspace }}

      # Run coverage for rlp
      - run: pnpm run coverage
        working-directory: ${{ github.workspace }}/packages/rlp

      # Run coverage for genesis
      - run: pnpm run coverage
        working-directory: ${{ github.workspace }}/packages/genesis

      # Upload code coverage for all jobs
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: static

