name: Spell check (cspell)
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-spellcheck-cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm run spellcheck
