name: Util
on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/util

defaults:
  run:
    working-directory: packages/util

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-util:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.cache-key }}

      - run: npm run coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: util

      - run: npm run lint
