name: Verkle
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        default: 'none'
      submodule-cache-key:
        required: false
        default: 'none'

env:
  cwd: ${{github.workspace}}/packages/verkle

defaults:
  run:
    working-directory: packages/verkle

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-verkle
  cancel-in-progress: true

jobs:
  test-verkle:
    if: contains(join(github.event.pull_request.labels.*.name, ' '), 'test verkle')
    runs-on: ubuntu-latest

    steps:
      # We clone the repo and submodules if triggered from work-flow dispatch
      - if: inputs.submodule-cache-key == 'none'
        uses: actions/checkout@v5

      # We restore the code/deps from cache if triggered from workflow_call (i.e. have valid cache key)
      - if: inputs.dep-cache-key != 'none' 
        uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
        working-directory: ${{ github.workspace }}

      - run: pnpm run test
