name: Verkle
on:
  workflow_call:
    inputs:
      cache-key:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      cache-key:
        required: false
        type: string

env:
  cwd: ${{github.workspace}}/packages/verkle

defaults:
  run:
    working-directory: packages/verkle

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-verkle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.cache-key }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --omit=peer

      - run: npm run lint
      - run: npm run test
